name = "gluple"
version = "2.2.0"
description = "Tuple methods for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "darky", repo = "gluple" }

[dependencies]
gleam_stdlib = ">= 0.67.1 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.9.0 and < 2.0.0"
cleam = ">= 2.0.0 and < 3.0.0"
